### ISSUE TITLE
Can `printWidth` be set separately for `className`?

### ISSUE THREAD

**Issue by u3u** [ony3000/prettier-plugin-classnames#21]
## Is your feature request related to a problem? Please describe

> Because this plugin replaces the original class name with a multi-line class name, the printWidth is based on the start of the class name, not the start of the line.

According to this description, `printWidth` starts from `className`, so it would be better to have a new option set specifically for it to ensure visual consistency!

## Describe the solution you'd like

For example, we can add a `customPrintWidth` or `customMaxLen` for the plugin. If not set, it will still read the `printWidth` option of Prettier by default.

**Comment by ony3000** [comment]
I'm considering a similar idea.

My idea is to add some kind of `position` property, and there are two options for this:

- `relative`: Use current criterion. This will be the default option considering backward compatibility.

  ```
  --------------------------------------------------| printWidth=50
  export function Callout({ children }) {
    return (
      <div
                  |--------------------------------------------------|
        className="bg-gray-100/50 border border-zinc-400/30
         |--------------------------------------------------|
          dark:bg-neutral-900/50 dark:border-neutral-500/30
          px-4 py-4 rounded-xl"
      >
        {children}
      </div>
    );
  }
  ```

- `absolute`: The `printWidth` will be based on the start of the line.

  ```
  --------------------------------------------------| printWidth=50
  export function Callout({ children }) {
    return (
      <div
        className="bg-gray-100/50 border
  border-zinc-400/30 dark:bg-neutral-900/50
  dark:border-neutral-500/30 px-4 py-4 rounded-xl"
      >
        {children}
      </div>
    );
  }
  ```

**Comment by ony3000** [comment]
@u3u `v0.5.0` has been released, check it out! :smile:
