### ISSUE TITLE
This plugin does not play nicely with the official "prettier-plugin-tailwindcss" plugin

### ISSUE THREAD

**Issue by jbccollins** [ony3000/prettier-plugin-classnames#31]
## Dependency information
For reference: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

The official prettier-plugin-tailwindcss will nicely sort your tailwind classes into an opinionated order. I would love to be able to use this classnames plugin, but unfortunately when I add it to my tailwind config it breaks the sorting that the official plugin provides.

## Steps to reproduce
Add these plugins to your .prettierrc.json: (order doesn't matter)
  "plugins": [
    "prettier-plugin-tailwindcss",
    "prettier-plugin-classnames"
  ]

## The current behavior
Class sorting breaks while line wrapping still works

## The expected behavior
Both class sorting and line wrapping work in harmony

**Comment by ony3000** [comment]
Have you checked the [last section](https://github.com/ony3000/prettier-plugin-classnames#compatibility-with-other-prettier-plugins) of the README?

**Comment by jbccollins** [comment]
Wow I am a dumbass. My apologies for raising this issue. Thanks for the help :)
