### ISSUE TITLE
Proposal: minAttributeWidth setting

### ISSUE THREAD

**Issue by gar1t** [ony3000/prettier-plugin-classnames#32]
It looks like the plugin uses `printWidth` to wrap, regardless of the attribute column start. `endingPosition` is used to align the wrapped portion of the text: indented under the attribute col start in the case of `relative` and a col 0 in the case of absolute.

In the case of `relative`, this leads to long lines as the break point occurs at attribute start + print width. In the case of `absolute` this leads to non-indented blocks of text.

IMO both are problematic. Either you have longer-than-expected lines or you have non-indented blocks.

If you introduce a config setting like `minAttributeWidth` the user could specify a min width used to calculate break points. The `relative` setting (default) would take the max value of "print width minus attribute start" and the new "min attribute width" setting, which could default to a value of `printWidth` to preserve the current behavior.

If I have this wrong, please lmk. My goal for our code base is to respect `printWidth` (absolute behavior) and maintain indents on wrapping (relative behavior).

Great plugin btw! It's indispensable for Tailwind's brave new world :)

**Comment by ony3000** [comment]
When implementing the `endingPosition` option, it occurred to me that there might be a need for indentation preservation. :joy:

There was also a suggestion in #21 for some kind of width option. However, since the position of the column where the attribute starts can vary from row to row, I will consider another method instead of the width option.

**Comment by gar1t** [comment]
My proposal takes the start position into consideration. It's not a width option but a min width. The behavior I'm proposing is standard for other indentation such as text blocks.

**Comment by ony3000** [comment]
Yes, I meant "a kind of width".

I understand this is a suggestion considering the starting position, and if applied to the example code in the README it would look something like this:

```
// minAttributeWidth(tentative name)=40 example:

--------------------------------------------------| printWidth=50
export function Callout({ children }) {
  return (
    <div
                |----------------------------------------| limit=40 (=minAttributeWidth)
      className="bg-gray-100/50 border border-zinc-400/30
       |------------------------------------------| limit=42 (=printWidth-8)
        dark:bg-neutral-900/50
        dark:border-neutral-500/30 px-4 py-4
        rounded-xl"
    >
      {children}
    </div>
  );
}
```

If an element has multiple levels of nesting, the start position of the attribute will be pushed to the right as the level of nesting increases, resulting in a line wrapping that is longer than the "absolute" ending position.

Therefore, I would avoid introducing such custom widths as much as possible.

**Comment by ony3000** [comment]
@gar1t `v0.6.0` has been released, check it out! :smile:

**Comment by gar1t** [comment]
Terrific enhancement - works great, thank you!

**Comment by u3u** [comment]
Thank you! Everything is perfect now! I noticed it at that time, but due to being too busy with work at the end of the year, I didn't have time to bring it up.
