### ISSUE TITLE
Support svelte parser

### ISSUE THREAD

**Issue by ony3000** [ony3000/prettier-plugin-classnames#42]

**Comment by sxxov** [comment]
Is there a list of things that need to be implemented before svelte can be supported? Would love to help/contribute.

**Comment by ony3000** [comment]
I don't have a list, but I would like to complete the following tasks before supporting the new parser:

- Reinforce testing of existing parsers and determine formatting policies (currently in progress)
- Refactoring of core parts
   - Modify the `ClassNameType` enum to be a combination of multiple properties
   (It feels similar to combining Tailwind CSS utility classes.)
   - Improve the process of finding class names in AST and wrapping them
   (I'm considering something like introducing an abstract class, but haven't thought about it in more detail.)

**Comment by ony3000** [comment]
Recent updates:

- As part of the core parts refactoring plan, modifications to the `ClassNameType` enum are complete.
- I decided to postpone improving the process of finding class names in AST and wrapping them around lines because no specific plan has been decided.
- Reinforce testing of existing parsers and determining formatting policies are almost complete.
