### ISSUE TITLE
New line per type regardless of line length

### ISSUE THREAD

**Issue by adriangalilea** [ony3000/prettier-plugin-classnames#48]
Thanks for the plugin!

Wanted to suggest what I intuitively think of the correct way of ordering.

This is what I currently get with the plugin:
<img width="666" alt="image" src="https://github.com/ony3000/prettier-plugin-classnames/assets/90320947/835e1e28-37e6-4c6f-868c-a2f1ac70c5dd">

 This is what I would like to see:
<img width="640" alt="image" src="https://github.com/ony3000/prettier-plugin-classnames/assets/90320947/93daf3e6-f40a-4361-b8d5-d72b2d4026e5">
or
<img width="632" alt="image" src="https://github.com/ony3000/prettier-plugin-classnames/assets/90320947/fda88274-272b-4ab2-84c3-703600f8ee75">
but the `"` feels a bit lonely there.

Perhaps this is not possible, or other people disagree, but figured I'd say it :)

**Comment by ony3000** [comment]
I know some people like to have lines break based on certain conditions (e.g. breakpoints), regardless of line length.

But unfortunately, (as you may have guessed) this is difficult to support.

There are two main reasons. One is that people have different preferences, so I cannot arbitrarily set the standard, and the other is that I do not want to make this plugin more complicated.

**Comment by adriangalilea** [comment]
> There are two main reasons. One is that people have different preferences, so I cannot arbitrarily set the standard, and the other is that I do not want to make this plugin more complicated.

Fair enough :)

I also had doubts when communicating the idea about what would be the "correct" order.

I guess one way to do it is setting an arbitrary order that seems reasonable but allowing tweaking it in a plain json file or directly in prettierrc if it's allowed.

In any case, you did enough already, so don't bother, thank you for sharing!
