### ISSUE TITLE
How can I use quote marks (') instead of speech marks (")

### ISSUE THREAD

**Issue by tuffstuff9** [ony3000/prettier-plugin-classnames#54]
instead of className="bg-blue-500", I would like to have className='bg-blue-500'. Adding this plugin changes the normal settings. How can I fix this? Thank you.

**Comment by ony3000** [comment]
This plugin performs Prettier's formatting before processing line wrapping.

Changing single quotes to double quotes is the default behavior of Prettier, regardless of whether you use this plugin or not, and unfortunately this default behavior cannot be fixed by changing the options.

**Comment by tuffstuff9** [comment]
Thanks for your response. If the plugin performs prettier's formatting before processing, shouldn't it maintain my original settings? I have 	`"singleQuote": true,` in my `.prettierrc`. Or do you mean that the plugin has its own prettier config which can't be changed?

**Comment by ony3000** [comment]
You can check this in the [Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAMQggApg8wALcgGwBNsE8BfAJR5gAHSh48PGEWzj6YiRIA8ncgDdm7AIYBnHQDktAWzgBeAOQAjAOYBaS+yJxbAVgAMb8wD4FiicFYObgQ+X2UAelU1H3E8AQBuMT4QABoQCAwKaB1kUC1sbAgAdwAFfIQclC12Iq0ATxy0y2wtMABrOBgAZWM4ABlyKDhkAmqdOCaW9s6ujFbB62QYbCc08aNyJZWJ1Ew4bHITWGqAFX2ofPI4StH2cbWF9jgARSIIeC3VkAArHTQux4vN4fJC3e4gACOwLgJUKGEqIF0tiGcE4qNSIGWWg4CwAwhAjEYtMhEex2BidICAIIwZbkSxEeAlfYDIYjMY7FgwIzsADqbHgOjmYDgXQq5AoagldRJYD0GLUTgAklA0bAumADpkqaqujA6k92XcdhhCuNeS0MCTTdd9mphmlBuNcLCtNYiUbwXNsM6SZYtJY4OS0qbBjBeeRODAWMgABxuNI8KHkHiu93E0EctIwAMRqMxpAAJjSRHGJwDNyzqCMgc4aM4fS0UGsRDdcFo2CJtIWJK0jIgID4fCAA), but even if the `singleQuote` option is enabled, the delimiter surrounding the class name is changed to double quotes.

**Comment by feitozabruno** [comment]
> You can check this in the [Prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAMwFcowYBLaPAMQggApg8wALcgGwBNsE8BfAJR5gAHSh48PGEWzj6YiRIA8ncgDdm7AIYBnHQDktAWzgBeAOQAjAOYBaS+yJxbAVgAMb8wD4FiicFYObgQ+X2UAelU1H3E8AQBuMT4QABoQCAwKaB1kUC1sbAgAdwAFfIQclC12Iq0ATxy0y2wtMABrOBgAZWM4ABlyKDhkAmqdOCaW9s6ujFbB62QYbCc08aNyJZWJ1Ew4bHITWGqAFX2ofPI4StH2cbWF9jgARSIIeC3VkAArHTQux4vN4fJC3e4gACOwLgJUKGEqIF0tiGcE4qNSIGWWg4CwAwhAjEYtMhEex2BidICAIIwZbkSxEeAlfYDIYjMY7FgwIzsADqbHgOjmYDgXQq5AoagldRJYD0GLUTgAklA0bAumADpkqaqujA6k92XcdhhCuNeS0MCTTdd9mphmlBuNcLCtNYiUbwXNsM6SZYtJY4OS0qbBjBeeRODAWMgABxuNI8KHkHiu93E0EctIwAMRqMxpAAJjSRHGJwDNyzqCMgc4aM4fS0UGsRDdcFo2CJtIWJK0jIgID4fCAA), but even if the `singleQuote` option is enabled, the delimiter surrounding the class name is changed to double quotes.

I'm experiencing the same problem, in the prettier playground it uses single quotes when the --jsx-single-quote option is enabled

**Comment by ony3000** [comment]
@feitozabruno Thank you for pointing out what I missed. I forgot about the `jsxSingleQuote` option because I don't usually use it.

**Comment by ony3000** [comment]
@tuffstuff9 @feitozabruno Fixed in `v0.6.6`, check it out!

**Comment by tuffstuff9** [comment]
> @tuffstuff9 @feitozabruno Fixed in `v0.6.6`, check it out!

Works perfectly - your prompt attention is much appreciated!
