### ISSUE TITLE
Compatibility with prettier-plugin-tailwindcss and prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by angrybacon** [ony3000/prettier-plugin-classnames#80]
## Dependency information

See version numbers here https://stackblitz.com/edit/vitejs-vite-nbvwr5?file=package.json&view=editor

### `index.html`

On my machine, Prettier errors out on the HTML file with the following:

```
[error] path/to/sample.html: SyntaxError: ';' expected. (3:16)
[error]   1 | <!doctype html>
[error]   2 | <html>
[error] > 3 |   <head>
[error]     |                ^
[error]   4 |     <title>Some Title</title>
[error]   5 |   </head>
[error]   6 |   <body>
[error]   1 | <!doctype html>
[error]   2 | <html>
[error] > 3 |   <head>
[error]     |                ^
[error]   4 |     <title>Some Title</title>
[error]   5 |   </head>
[error]   6 |   <body>
All matched files use Prettier code style!
```

However in the sandbox it will only (correctly) report the uppercase `DOCTYPE` with no error. On my machine, the error goes away when I empty the `<script>`

```diff
 <script id="__NEXT_DATA__" type="application/json">
   {
-    "props": {
-      "pageProps": {
-        "appSettings": {
-          "ENVIRONMENT": "production"
-        },
-        "initialReduxState": {}
-      }
-    }
   }
 </script>
```

### `sample.md`

Can't reproduce in the sandbox. Locally the 2nd block _correctly_ (I don't want it, but I understand why it's there) receives the `;`, but so does the first code block, which shouldn't end with a semi colon

```diff
-<div />
+<div />;
```

## The expected behavior

It's a bit deceptive to write the following since it does work as expected in the sandbox...

- No semi-colon added inside of JSX-like Markdown code blocks for single nodes
- Ability to parse HTML

**Comment by ony3000** [comment]
@angrybacon Fixed in `v0.7.5`, check it out!

**Comment by ony3000** [comment]
From what I've investigated, the issue isn't reproducible in the sandbox because `prettier.config.ts` isn't Prettier's configuration file.

For your information, the markdown code block issue is reproducible in the case of using it with `prettier-plugin-merge`, so I am working on it.

**Comment by angrybacon** [comment]
Oh that makes sense

> I am working on it

I can confirm that thanks for the headsup, is this being tracked somewhere already?

**Comment by ony3000** [comment]
This wasn't reported, I just discovered it during my own inspection after the release of `v0.7.5`.

**Comment by angrybacon** [comment]
This works for me, thanks a lot for the responsiveness!
